// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chatSystem/ent/chatroom"
	"chatSystem/ent/chatroommember"
	"chatSystem/ent/predicate"
	"chatSystem/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatRoomMemberQuery is the builder for querying ChatRoomMember entities.
type ChatRoomMemberQuery struct {
	config
	ctx        *QueryContext
	order      []chatroommember.OrderOption
	inters     []Interceptor
	predicates []predicate.ChatRoomMember
	withUser   *UserQuery
	withRoom   *ChatRoomQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChatRoomMemberQuery builder.
func (crmq *ChatRoomMemberQuery) Where(ps ...predicate.ChatRoomMember) *ChatRoomMemberQuery {
	crmq.predicates = append(crmq.predicates, ps...)
	return crmq
}

// Limit the number of records to be returned by this query.
func (crmq *ChatRoomMemberQuery) Limit(limit int) *ChatRoomMemberQuery {
	crmq.ctx.Limit = &limit
	return crmq
}

// Offset to start from.
func (crmq *ChatRoomMemberQuery) Offset(offset int) *ChatRoomMemberQuery {
	crmq.ctx.Offset = &offset
	return crmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (crmq *ChatRoomMemberQuery) Unique(unique bool) *ChatRoomMemberQuery {
	crmq.ctx.Unique = &unique
	return crmq
}

// Order specifies how the records should be ordered.
func (crmq *ChatRoomMemberQuery) Order(o ...chatroommember.OrderOption) *ChatRoomMemberQuery {
	crmq.order = append(crmq.order, o...)
	return crmq
}

// QueryUser chains the current query on the "user" edge.
func (crmq *ChatRoomMemberQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: crmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatroommember.Table, chatroommember.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, chatroommember.UserTable, chatroommember.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(crmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoom chains the current query on the "room" edge.
func (crmq *ChatRoomMemberQuery) QueryRoom() *ChatRoomQuery {
	query := (&ChatRoomClient{config: crmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatroommember.Table, chatroommember.FieldID, selector),
			sqlgraph.To(chatroom.Table, chatroom.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, chatroommember.RoomTable, chatroommember.RoomColumn),
		)
		fromU = sqlgraph.SetNeighbors(crmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChatRoomMember entity from the query.
// Returns a *NotFoundError when no ChatRoomMember was found.
func (crmq *ChatRoomMemberQuery) First(ctx context.Context) (*ChatRoomMember, error) {
	nodes, err := crmq.Limit(1).All(setContextOp(ctx, crmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chatroommember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (crmq *ChatRoomMemberQuery) FirstX(ctx context.Context) *ChatRoomMember {
	node, err := crmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChatRoomMember ID from the query.
// Returns a *NotFoundError when no ChatRoomMember ID was found.
func (crmq *ChatRoomMemberQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = crmq.Limit(1).IDs(setContextOp(ctx, crmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chatroommember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (crmq *ChatRoomMemberQuery) FirstIDX(ctx context.Context) int {
	id, err := crmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChatRoomMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChatRoomMember entity is found.
// Returns a *NotFoundError when no ChatRoomMember entities are found.
func (crmq *ChatRoomMemberQuery) Only(ctx context.Context) (*ChatRoomMember, error) {
	nodes, err := crmq.Limit(2).All(setContextOp(ctx, crmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chatroommember.Label}
	default:
		return nil, &NotSingularError{chatroommember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (crmq *ChatRoomMemberQuery) OnlyX(ctx context.Context) *ChatRoomMember {
	node, err := crmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChatRoomMember ID in the query.
// Returns a *NotSingularError when more than one ChatRoomMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (crmq *ChatRoomMemberQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = crmq.Limit(2).IDs(setContextOp(ctx, crmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chatroommember.Label}
	default:
		err = &NotSingularError{chatroommember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (crmq *ChatRoomMemberQuery) OnlyIDX(ctx context.Context) int {
	id, err := crmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChatRoomMembers.
func (crmq *ChatRoomMemberQuery) All(ctx context.Context) ([]*ChatRoomMember, error) {
	ctx = setContextOp(ctx, crmq.ctx, ent.OpQueryAll)
	if err := crmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChatRoomMember, *ChatRoomMemberQuery]()
	return withInterceptors[[]*ChatRoomMember](ctx, crmq, qr, crmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (crmq *ChatRoomMemberQuery) AllX(ctx context.Context) []*ChatRoomMember {
	nodes, err := crmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChatRoomMember IDs.
func (crmq *ChatRoomMemberQuery) IDs(ctx context.Context) (ids []int, err error) {
	if crmq.ctx.Unique == nil && crmq.path != nil {
		crmq.Unique(true)
	}
	ctx = setContextOp(ctx, crmq.ctx, ent.OpQueryIDs)
	if err = crmq.Select(chatroommember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (crmq *ChatRoomMemberQuery) IDsX(ctx context.Context) []int {
	ids, err := crmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (crmq *ChatRoomMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, crmq.ctx, ent.OpQueryCount)
	if err := crmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, crmq, querierCount[*ChatRoomMemberQuery](), crmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (crmq *ChatRoomMemberQuery) CountX(ctx context.Context) int {
	count, err := crmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (crmq *ChatRoomMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, crmq.ctx, ent.OpQueryExist)
	switch _, err := crmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (crmq *ChatRoomMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := crmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChatRoomMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (crmq *ChatRoomMemberQuery) Clone() *ChatRoomMemberQuery {
	if crmq == nil {
		return nil
	}
	return &ChatRoomMemberQuery{
		config:     crmq.config,
		ctx:        crmq.ctx.Clone(),
		order:      append([]chatroommember.OrderOption{}, crmq.order...),
		inters:     append([]Interceptor{}, crmq.inters...),
		predicates: append([]predicate.ChatRoomMember{}, crmq.predicates...),
		withUser:   crmq.withUser.Clone(),
		withRoom:   crmq.withRoom.Clone(),
		// clone intermediate query.
		sql:  crmq.sql.Clone(),
		path: crmq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (crmq *ChatRoomMemberQuery) WithUser(opts ...func(*UserQuery)) *ChatRoomMemberQuery {
	query := (&UserClient{config: crmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crmq.withUser = query
	return crmq
}

// WithRoom tells the query-builder to eager-load the nodes that are connected to
// the "room" edge. The optional arguments are used to configure the query builder of the edge.
func (crmq *ChatRoomMemberQuery) WithRoom(opts ...func(*ChatRoomQuery)) *ChatRoomMemberQuery {
	query := (&ChatRoomClient{config: crmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crmq.withRoom = query
	return crmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		JoinedAt time.Time `json:"joined_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChatRoomMember.Query().
//		GroupBy(chatroommember.FieldJoinedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (crmq *ChatRoomMemberQuery) GroupBy(field string, fields ...string) *ChatRoomMemberGroupBy {
	crmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChatRoomMemberGroupBy{build: crmq}
	grbuild.flds = &crmq.ctx.Fields
	grbuild.label = chatroommember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		JoinedAt time.Time `json:"joined_at,omitempty"`
//	}
//
//	client.ChatRoomMember.Query().
//		Select(chatroommember.FieldJoinedAt).
//		Scan(ctx, &v)
func (crmq *ChatRoomMemberQuery) Select(fields ...string) *ChatRoomMemberSelect {
	crmq.ctx.Fields = append(crmq.ctx.Fields, fields...)
	sbuild := &ChatRoomMemberSelect{ChatRoomMemberQuery: crmq}
	sbuild.label = chatroommember.Label
	sbuild.flds, sbuild.scan = &crmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChatRoomMemberSelect configured with the given aggregations.
func (crmq *ChatRoomMemberQuery) Aggregate(fns ...AggregateFunc) *ChatRoomMemberSelect {
	return crmq.Select().Aggregate(fns...)
}

func (crmq *ChatRoomMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range crmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, crmq); err != nil {
				return err
			}
		}
	}
	for _, f := range crmq.ctx.Fields {
		if !chatroommember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if crmq.path != nil {
		prev, err := crmq.path(ctx)
		if err != nil {
			return err
		}
		crmq.sql = prev
	}
	return nil
}

func (crmq *ChatRoomMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChatRoomMember, error) {
	var (
		nodes       = []*ChatRoomMember{}
		_spec       = crmq.querySpec()
		loadedTypes = [2]bool{
			crmq.withUser != nil,
			crmq.withRoom != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChatRoomMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChatRoomMember{config: crmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, crmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := crmq.withUser; query != nil {
		if err := crmq.loadUser(ctx, query, nodes, nil,
			func(n *ChatRoomMember, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := crmq.withRoom; query != nil {
		if err := crmq.loadRoom(ctx, query, nodes, nil,
			func(n *ChatRoomMember, e *ChatRoom) { n.Edges.Room = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (crmq *ChatRoomMemberQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*ChatRoomMember, init func(*ChatRoomMember), assign func(*ChatRoomMember, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ChatRoomMember)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (crmq *ChatRoomMemberQuery) loadRoom(ctx context.Context, query *ChatRoomQuery, nodes []*ChatRoomMember, init func(*ChatRoomMember), assign func(*ChatRoomMember, *ChatRoom)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ChatRoomMember)
	for i := range nodes {
		fk := nodes[i].RoomID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chatroom.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "room_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (crmq *ChatRoomMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := crmq.querySpec()
	_spec.Node.Columns = crmq.ctx.Fields
	if len(crmq.ctx.Fields) > 0 {
		_spec.Unique = crmq.ctx.Unique != nil && *crmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, crmq.driver, _spec)
}

func (crmq *ChatRoomMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chatroommember.Table, chatroommember.Columns, sqlgraph.NewFieldSpec(chatroommember.FieldID, field.TypeInt))
	_spec.From = crmq.sql
	if unique := crmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if crmq.path != nil {
		_spec.Unique = true
	}
	if fields := crmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatroommember.FieldID)
		for i := range fields {
			if fields[i] != chatroommember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if crmq.withUser != nil {
			_spec.Node.AddColumnOnce(chatroommember.FieldUserID)
		}
		if crmq.withRoom != nil {
			_spec.Node.AddColumnOnce(chatroommember.FieldRoomID)
		}
	}
	if ps := crmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := crmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := crmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := crmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (crmq *ChatRoomMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(crmq.driver.Dialect())
	t1 := builder.Table(chatroommember.Table)
	columns := crmq.ctx.Fields
	if len(columns) == 0 {
		columns = chatroommember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if crmq.sql != nil {
		selector = crmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if crmq.ctx.Unique != nil && *crmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range crmq.predicates {
		p(selector)
	}
	for _, p := range crmq.order {
		p(selector)
	}
	if offset := crmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := crmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChatRoomMemberGroupBy is the group-by builder for ChatRoomMember entities.
type ChatRoomMemberGroupBy struct {
	selector
	build *ChatRoomMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (crmgb *ChatRoomMemberGroupBy) Aggregate(fns ...AggregateFunc) *ChatRoomMemberGroupBy {
	crmgb.fns = append(crmgb.fns, fns...)
	return crmgb
}

// Scan applies the selector query and scans the result into the given value.
func (crmgb *ChatRoomMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crmgb.build.ctx, ent.OpQueryGroupBy)
	if err := crmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatRoomMemberQuery, *ChatRoomMemberGroupBy](ctx, crmgb.build, crmgb, crmgb.build.inters, v)
}

func (crmgb *ChatRoomMemberGroupBy) sqlScan(ctx context.Context, root *ChatRoomMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(crmgb.fns))
	for _, fn := range crmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*crmgb.flds)+len(crmgb.fns))
		for _, f := range *crmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*crmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChatRoomMemberSelect is the builder for selecting fields of ChatRoomMember entities.
type ChatRoomMemberSelect struct {
	*ChatRoomMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (crms *ChatRoomMemberSelect) Aggregate(fns ...AggregateFunc) *ChatRoomMemberSelect {
	crms.fns = append(crms.fns, fns...)
	return crms
}

// Scan applies the selector query and scans the result into the given value.
func (crms *ChatRoomMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crms.ctx, ent.OpQuerySelect)
	if err := crms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatRoomMemberQuery, *ChatRoomMemberSelect](ctx, crms.ChatRoomMemberQuery, crms, crms.inters, v)
}

func (crms *ChatRoomMemberSelect) sqlScan(ctx context.Context, root *ChatRoomMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(crms.fns))
	for _, fn := range crms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*crms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
