// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chatSystem/ent/chatroommember"
	"chatSystem/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatRoomMemberDelete is the builder for deleting a ChatRoomMember entity.
type ChatRoomMemberDelete struct {
	config
	hooks    []Hook
	mutation *ChatRoomMemberMutation
}

// Where appends a list predicates to the ChatRoomMemberDelete builder.
func (crmd *ChatRoomMemberDelete) Where(ps ...predicate.ChatRoomMember) *ChatRoomMemberDelete {
	crmd.mutation.Where(ps...)
	return crmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (crmd *ChatRoomMemberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, crmd.sqlExec, crmd.mutation, crmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (crmd *ChatRoomMemberDelete) ExecX(ctx context.Context) int {
	n, err := crmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (crmd *ChatRoomMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chatroommember.Table, sqlgraph.NewFieldSpec(chatroommember.FieldID, field.TypeInt))
	if ps := crmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, crmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	crmd.mutation.done = true
	return affected, err
}

// ChatRoomMemberDeleteOne is the builder for deleting a single ChatRoomMember entity.
type ChatRoomMemberDeleteOne struct {
	crmd *ChatRoomMemberDelete
}

// Where appends a list predicates to the ChatRoomMemberDelete builder.
func (crmdo *ChatRoomMemberDeleteOne) Where(ps ...predicate.ChatRoomMember) *ChatRoomMemberDeleteOne {
	crmdo.crmd.mutation.Where(ps...)
	return crmdo
}

// Exec executes the deletion query.
func (crmdo *ChatRoomMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := crmdo.crmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chatroommember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (crmdo *ChatRoomMemberDeleteOne) ExecX(ctx context.Context) {
	if err := crmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
