// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chatSystem/ent/chatroom"
	"chatSystem/ent/chatroommember"
	"chatSystem/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatRoomMemberCreate is the builder for creating a ChatRoomMember entity.
type ChatRoomMemberCreate struct {
	config
	mutation *ChatRoomMemberMutation
	hooks    []Hook
}

// SetJoinedAt sets the "joined_at" field.
func (crmc *ChatRoomMemberCreate) SetJoinedAt(t time.Time) *ChatRoomMemberCreate {
	crmc.mutation.SetJoinedAt(t)
	return crmc
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (crmc *ChatRoomMemberCreate) SetNillableJoinedAt(t *time.Time) *ChatRoomMemberCreate {
	if t != nil {
		crmc.SetJoinedAt(*t)
	}
	return crmc
}

// SetUserID sets the "user_id" field.
func (crmc *ChatRoomMemberCreate) SetUserID(i int) *ChatRoomMemberCreate {
	crmc.mutation.SetUserID(i)
	return crmc
}

// SetRoomID sets the "room_id" field.
func (crmc *ChatRoomMemberCreate) SetRoomID(i int) *ChatRoomMemberCreate {
	crmc.mutation.SetRoomID(i)
	return crmc
}

// SetUser sets the "user" edge to the User entity.
func (crmc *ChatRoomMemberCreate) SetUser(u *User) *ChatRoomMemberCreate {
	return crmc.SetUserID(u.ID)
}

// SetRoom sets the "room" edge to the ChatRoom entity.
func (crmc *ChatRoomMemberCreate) SetRoom(c *ChatRoom) *ChatRoomMemberCreate {
	return crmc.SetRoomID(c.ID)
}

// Mutation returns the ChatRoomMemberMutation object of the builder.
func (crmc *ChatRoomMemberCreate) Mutation() *ChatRoomMemberMutation {
	return crmc.mutation
}

// Save creates the ChatRoomMember in the database.
func (crmc *ChatRoomMemberCreate) Save(ctx context.Context) (*ChatRoomMember, error) {
	crmc.defaults()
	return withHooks(ctx, crmc.sqlSave, crmc.mutation, crmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (crmc *ChatRoomMemberCreate) SaveX(ctx context.Context) *ChatRoomMember {
	v, err := crmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (crmc *ChatRoomMemberCreate) Exec(ctx context.Context) error {
	_, err := crmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (crmc *ChatRoomMemberCreate) ExecX(ctx context.Context) {
	if err := crmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (crmc *ChatRoomMemberCreate) defaults() {
	if _, ok := crmc.mutation.JoinedAt(); !ok {
		v := chatroommember.DefaultJoinedAt()
		crmc.mutation.SetJoinedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (crmc *ChatRoomMemberCreate) check() error {
	if _, ok := crmc.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "ChatRoomMember.joined_at"`)}
	}
	if _, ok := crmc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ChatRoomMember.user_id"`)}
	}
	if _, ok := crmc.mutation.RoomID(); !ok {
		return &ValidationError{Name: "room_id", err: errors.New(`ent: missing required field "ChatRoomMember.room_id"`)}
	}
	if len(crmc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ChatRoomMember.user"`)}
	}
	if len(crmc.mutation.RoomIDs()) == 0 {
		return &ValidationError{Name: "room", err: errors.New(`ent: missing required edge "ChatRoomMember.room"`)}
	}
	return nil
}

func (crmc *ChatRoomMemberCreate) sqlSave(ctx context.Context) (*ChatRoomMember, error) {
	if err := crmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := crmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, crmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	crmc.mutation.id = &_node.ID
	crmc.mutation.done = true
	return _node, nil
}

func (crmc *ChatRoomMemberCreate) createSpec() (*ChatRoomMember, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatRoomMember{config: crmc.config}
		_spec = sqlgraph.NewCreateSpec(chatroommember.Table, sqlgraph.NewFieldSpec(chatroommember.FieldID, field.TypeInt))
	)
	if value, ok := crmc.mutation.JoinedAt(); ok {
		_spec.SetField(chatroommember.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if nodes := crmc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   chatroommember.UserTable,
			Columns: []string{chatroommember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := crmc.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   chatroommember.RoomTable,
			Columns: []string{chatroommember.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoomID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatRoomMemberCreateBulk is the builder for creating many ChatRoomMember entities in bulk.
type ChatRoomMemberCreateBulk struct {
	config
	err      error
	builders []*ChatRoomMemberCreate
}

// Save creates the ChatRoomMember entities in the database.
func (crmcb *ChatRoomMemberCreateBulk) Save(ctx context.Context) ([]*ChatRoomMember, error) {
	if crmcb.err != nil {
		return nil, crmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(crmcb.builders))
	nodes := make([]*ChatRoomMember, len(crmcb.builders))
	mutators := make([]Mutator, len(crmcb.builders))
	for i := range crmcb.builders {
		func(i int, root context.Context) {
			builder := crmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatRoomMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, crmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, crmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, crmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (crmcb *ChatRoomMemberCreateBulk) SaveX(ctx context.Context) []*ChatRoomMember {
	v, err := crmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (crmcb *ChatRoomMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := crmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (crmcb *ChatRoomMemberCreateBulk) ExecX(ctx context.Context) {
	if err := crmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
